# Generated by Django 2.2.12 on 2020-05-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Group',
        ),
    ]
