# Generated by Django 2.2.12 on 2020-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200507_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
