# Generated by Django 2.2.12 on 2020-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200508_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=14),
        ),
    ]
